# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := SystemClockCoroutineTest
ARDUINO_LIBS := AUnit AceCommon AceRoutine AceSorting AceTime AceTimeClock
include ../../../EpoxyDuino/EpoxyDuino.mk
