# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloStm32F1Clock
ARDUINO_LIBS := AceCommon AceSorting AceTime AceTimeClock
include ../../../EpoxyDuino/EpoxyDuino.mk
