# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HardwareTest
ARDUINO_LIBS := AUnit AceCommon AceTime AceTimeClock
include ../../../EpoxyDuino/EpoxyDuino.mk
