# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloDS3231Clock
ARDUINO_LIBS := AceCommon AceSorting AceTime AceTimeClock AceWire
include ../../../EpoxyDuino/EpoxyDuino.mk
